.deploy_environment:
  image: docker:19.03.1-dind

stages:
  - build_dev
  - deploy_dev

build_dev: 
  only:
    - dev
  tags:
    - base-runner
  stage: build_dev
  extends: .deploy_environment
  script:
    - docker build -t tarkibuz/backend

deploy_dev:
  stage: deploy_dev
  only:
  - dev
  tags:
  - base-runner
  extends: .deploy_environment
  script:
    - docker service update --image tarkibuz/backend:latest dev_backend --force