services:
  postgres:
    container_name: postgres
    image: postgres
    networks:
      tarkib:
        aliases:
          - postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: app
    image: app:latest
    networks:
      tarkib:
        aliases:
          - app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@postgres:5432/$${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - MINIO_URL=http://minio:9000

networks:
  tarkib:

volumes:
  pg-data:
  redis-data:
  minio-data:
