services:
  app-news:
    build: .
    container_name: app-news
    networks:
      tarkib:
        aliases:
          - app-news
    env_file: 
      - .env
    ports:
      - "8888:8888"


  postgres:
    container_name: postgres
    image: postgres
    networks:
      tarkib:
        aliases:
          - postgres
    volumes:
      - pg-data:/var/lib/postgresql/datatarkibuz
    env_file: .env
    ports:
      - "5431:5432"
    
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8889:8080"
    networks:
      - tarkib


  # minio:
  #   container_name: minio-news
  #   image: bitnami/minio:2022
  #   networks:
  #     tarkib:
  #       aliases:
  #         - minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   env_file: .env
  #   volumes:
  #     - minio-data:/data
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "curl -f http://localhost:9000/minio/health/live || exit 1",
  #       ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5


networks:
  tarkib:

volumes:
  pg-data:
  # minio-data: